apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jobset.yaml

# Add required patches.
patches:
  # Remove namespace from the JobSet release manifests.
  - path: patches/jobset_remove_namespace.yaml
    target:
      group: ""
      version: v1
      kind: Namespace
